title: Article

fields:
  title:
    label: Titre
    type:  text
  icone:
    label: Icônes 
    type: selector
    mode: single
  text:
    label: Texte
    type:  markdown
  dates: 
    label: Dates
    type: structure
    entry: >
      {{title}} — {{moment}} — {{hours}} — {{place}}
    fields:
      title:
        label: Titre
        type: text
      moment: 
        label: Date
        type: date
      hours: 
        label: Heures
        type: text
      place: 
        label: Lieu
        type: text
    help: Informations à afficher dans l'agenda
  actus:
    label: Afficher cette page comme une actu sur la page d'accueil ?
    type: radio
    default: non
    options:
      oui: oui
      non: non

