title: Article

fields:
  title:
    label: Titre
    type:  text
  icone:
    label: Icônes 
    type: selector
    mode: single
  text:
    label: Texte
    type:  markdown
  actus:
    label: Afficher cette page comme une actu sur la page d'accueil ?
    type: radio
    default: non
    options:
      oui: oui
      non: non

