title: Article

fields:
  title:
    label: Titre
    type:  text
  icone:
    label: Icônes 
    type: selector
    mode: single
    options: query
    query:
      page: /
      fetch: images
      value: '{{filename}}'
      text: '{{filename}}'
      flip: true
  text:
    label: Texte
    type:  markdown
  dates: 
    label: Dates
    type: structure
    entry: >
      {{title}} — {{moment}} - Du {{from}} au {{to}} — {{hours}} — {{place}}<br>
      {{link}} 
    fields:
      title:
        label: Titre
        type: text
      type:
        label: Type
        type: text
      moment:
        label: Date
        type: date
      from:
        label: Du
        type: date
        format: DD-MM-YYYY
      to: 
        label: Au
        type: date
        format: DD-MM-YYYY
      hours: 
        label: Heures
        type: text
      place: 
        label: Lieu
        type: text
      link: 
        label: Lien
        type: text
      agenda: 
        label: Afficher cette page dans l'agenda ?
        type: radio
        default: oui
        options:
          oui: oui
          non: non
      actus:
        label: Afficher cette page comme une actu sur la page d'accueil ?
        type: radio
        default: non
        options:
          oui: oui
          non: non
    help: Informations à afficher dans l'agenda

