title: Article

fields:
  title:
    label: Titre
    type:  text
  icone:
    label: Icônes 
    type: selector
    mode: single
    options: query
    query:
      page: /
      fetch: images
      value: '{{filename}}'
      text: '{{filename}}'
      flip: true
  text:
    label: Texte
    type:  markdown
  billeterie: 
    label: Lien vers la billeterie
    type: url
  dates: 
    label: Dates
    type: structure
    entry: >
      {{title}} <br> {{personne}} <br> Du {{from}} au {{to}} <br> {{hours}} <br> {{place}}<br>
      {{link}} <br>
      Afficher cette page dans la {{home}} de la page d'accueil
    fields:
      title:
        label: Titre
        type: text
      type:
        label: Type
        type: text
      personne:
        label: Personne(s)
        type: text
      from:
        label: Du
        type: date
        format: DD-MM-YYYY
      to: 
        label: Au
        type: date
        format: DD-MM-YYYY
      hours: 
        label: Heures
        type: text
      place: 
        label: Lieu
        type: text
      link: 
        label: Lien
        type: text
      agenda: 
        label: Afficher cette page dans l'agenda ?
        type: radio
        default: oui
        options:
          oui: oui
          non: non
      home: 
        label: Afficher cette page sur dans une colonne de la page d'accueil ? 
        type: checkboxes
        require: false
        options:
          col1: Colonne 1
          col2: Colonne 2
          col3: Colonne 3

