title: Site

pages: true
files: true

fields:
  title:
    label: Title
    type:  text

  logo:
    label: Logo
    type:  text

  shortcut:
    label: Petit Logo
    type:  text



  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea

  address: 
    label : Coordonnées
    type: markdown

