title: Site

pages: true
files: true

fields:
  title:
    label: Title
    type:  text

  logo:
    label: Logo
    type:  text

  shortcut:
    label: Petit Logo
    type:  text


  # pdf:
  #   label: Pdfs à télécharger
  #   type: structure
  #   entry: >
  #     {{title}}<br />
  #     {{link}}
  #   fields: 
  #     title:
  #       label: Nom à afficher
  #       type: text
  #     link: 
  #       label: Choisir le Pdf
  #       type: select
  #       options: documents
  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea

  pdf:
    label: Pdfs à télécharger
    type: structure
    entry: >
      {{title}}<br />
      {{link}}
    fields: 
      title:
        label: Nom à afficher
        type: text
      link: 
        label: Choisir le Pdf
        type: select
        options: documents

  address: 
    label : Coordonnées
    type: markdown

