title: Site

pages: true
files: true

fields:
  title:
    label: Title
    type:  text
  logo:
    label: Logo
    type:  text
  shortcut:
    label: Petit Logo
    type:  text
  author:
    label: Author
    type:  text
  description:
    label: Description
    type:  textarea
  copyright:
    label: Copyright
    type:  textarea
  flottant:
    label: Activer ou non les éléments de menu flottant pour la Bulle et Jeunes Gens Modernes
    type: checkboxes
    options: 
      bulle: La bulle
      jgm: Jeunes Gens Modernes
  pdf:
    label: Pdfs à télécharger
    type: structure
    entry: >
      {{title}}<br />
      {{link}}
    fields: 
      title:
        label: Nom à afficher
        type: text
      link: 
        label: Choisir le Pdf
        type: select
        options: documents
  ogimage:
    label: Site Thumbnail
    type:  url
    help:  URL de l'image qui va représenter votre site sur les réseaux sociaux
  socialnetworks:
    label: Vos Réseaux Sociaux
    type:  structure
    entry: >
      {{title}} — {{link}}
    fields:
      title:
        label: Titre
        type:  text
        width: 1/2
      link:
        label: Lien
        type:  text
        width: 1/2
        icon:  link
  address: 
    label : Coordonnées
    type: markdown

